<?xml version="1.0" encoding="utf-8"?>
<Database Name="Test" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customers">
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>